# This is a basic workflow to help you get started with Actions
name: CI/CD

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_process:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Deploy Processing LAMBDA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: montudor/action-zip@v0.1.0
      - name: Zip Processing
        run: zip -qq -r ./aoc_bot.zip *
        working-directory: .
      - name: Deploy processing to LAMBDA
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: us-east-1
          function_name: aoc_check_lambda
          zip_file: ./aoc_bot.zip