# This is a basic workflow to help you get started with Actions
name: CI/CD

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_process:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Deploy Processing LAMBDA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: zip -j aoc_bot.zip ./*.py
      - run: aws lambda update-function-code --function-name=aoc_check_lambda  --zip-file=fileb://aoc_bot.zip